name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies using Makefile
      run: make install  # This will call the install target in your Makefile

    - name: Run the server
      run: |
        make run &
        sleep 10  # Allow time for the server to start up

    - name: Verify server is running
      run: |
        curl --fail http://localhost:3000 || exit 1

    - name: Stop the server
      run: |
        kill $(jobs -p) || true  # Kill the background server process if running
    
    - name: Lint with flake8
      run: make lint  # Calls the lint target in your Makefile
    
    - name: Test with pytest
      run: make test  # Calls the test target in your Makefile

