name: Python application workflow for LSA Search Engine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Install dependencies using Makefile
      run: make install  # Runs the 'make install' command to install dependencies

    - name: Run the server
      run: |
        make run &  # Start the server in the background
        sleep 10  # Wait for 10 seconds to allow the server to start

    - name: Verify server is running
      run: |
        curl --fail http://localhost:3000 || exit 1  # Check if the server is up and running

    - name: Stop the server
      run: |
        kill $(jobs -p) || true  # Stop the server by killing the background process
