# This workflow will install Python dependencies, run tests, and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # Install dependencies using the Makefile
    - name: Install dependencies
      run: make install

    # Run the Flask server and wait for it to start
    - name: Start Flask server
      run: |
        make run &
        sleep 10  # Adjust this if the server needs more or less time to start

    # (Optional) Test server responses or functionality after it is up and running
    - name: Run tests (optional)
      run: |
        curl http://localhost:3000  # Example of a test, you can replace with your actual test logic

    # Lint the code
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --exclude=venv --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --exclude=venv --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
