name: Python application workflow for LSA Search Engine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Remove old venv if exists
      run: |
        if [ -d "venv" ]; then rm -rf venv; fi
    
    - name: Install dependencies using Makefile
      run: make install  # This will call the 'install' target in your Makefile

    - name: Run the Flask server
      run: |
        make run &  # Start the Flask server in the background
        sleep 15  # Wait 15 seconds for the server to start

    - name: Verify server is running
      run: |
        curl --fail http://localhost:3000 || exit 1  # Check if the server is running

    - name: Stop the server
      run: |
        kill $(jobs -p) || true  # Kill the server process
